import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { pathToFileURL } from 'node:url'
import { parseSchemaDir } from '../tl/parser.js'
import { protocolSchemaDir as bundledSchemaDir } from '../index.js'
import type { TlDef, TlType } from '../tl/ir.js'

/**
 * Generates `generated/schema.ts` — TypeScript types for the **newest** layer:
 * one interface per constructor, a union alias per TL type, and an `RpcMethods`
 * map (method name → { params; result }) for typed worker handlers.
 *
 * Types only (no runtime). Field shapes are the post-`fromJson` values workers
 * receive: long→bigint, bytes/int128/int256→Buffer, Vector<T>→T[], flags.N?T→
 * optional. Run `yarn gen:types` after editing the schema.
 *
 *   yarn workspace @mt-tl/tl run gen:types
 */

const SPECIAL_TYPES = new Set(['Object', 'X', 'Bool', 'Vector t', 'true', '#'])

function tsName(name: string): string {
    return name
        .split('.')
        .map(s => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s))
        .join('')
}

function mapType(t: TlType, known: Set<string>): string {
    switch (t.kind) {
        case 'int':
        case 'double':
        case 'flags':
            return 'number'
        case 'long':
            return 'bigint'
        case 'bytes':
        case 'int128':
        case 'int256':
            return 'Buffer'
        case 'string':
            return 'string'
        case 'bool':
            return 'boolean'
        case 'true':
            return 'true'
        case 'vector':
            return `${wrapUnion(mapType(t.inner, known))}[]`
        case 'object':
            return 'unknown'
        case 'flag':
            return mapType(t.inner, known)
        case 'boxed':
        case 'bare': {
            const n = tsName(t.name)
            return known.has(n) ? n : 'unknown'
        }
    }
}

function wrapUnion(t: string): string {
    return t.includes('|') ? `(${t})` : t
}

function fieldLines(def: TlDef, known: Set<string>): string[] {
    const out: string[] = []
    for (const p of def.params) {
        if (p.type.kind === 'flags') continue // internal bitmask
        const prop = /^[A-Za-z_$][\w$]*$/.test(p.name) ? p.name : JSON.stringify(p.name)
        if (p.type.kind === 'flag') {
            out.push(`    ${prop}?: ${mapType(p.type.inner, known)}`)
        } else {
            out.push(`    ${prop}: ${mapType(p.type, known)}`)
        }
    }
    return out
}

/**
 * Generates TypeScript types from the `.tl` schema in `dir`: one interface per
 * constructor, a union per type, and the `RpcMethods` map (method → params/result)
 * you pass to `createServer<RpcMethods>()`. Returns the source as a string; see
 * {@link writeSchemaTs} to write it to a file. Run via your app's `gen:types` script.
 */
export function generateSchemaTs(dir: string = bundledSchemaDir): string {
    const { defs } = parseSchemaDir(dir)

    const ctors = defs.filter(d => d.kind === 'constructor')
    const methods = defs.filter(d => d.kind === 'method')

    // Type groups (union of constructors), excluding special types.
    const typeGroups = new Map<string, TlDef[]>()
    for (const d of ctors) {
        if (SPECIAL_TYPES.has(d.type)) continue
        const g = typeGroups.get(d.type) ?? []
        g.push(d)
        typeGroups.set(d.type, g)
    }

    // A TL type is a UNION of its constructors, emitted under the bare type name.
    // The one exception: a type with a single constructor whose name equals the
    // type name (e.g. `error` = Error) — there the lone interface IS the type, so
    // no union alias is needed.
    const unions = new Map<string, TlDef[]>()
    for (const [type, group] of typeGroups) {
        const name = tsName(type)
        const soleSelfNamed = group.length === 1 && tsName(group[0]!.name) === name
        if (soleSelfNamed) continue
        unions.set(name, group)
    }
    const unionNames = new Set(unions.keys())

    // A constructor's interface name. When it would take a name a union already
    // owns (the type's "primary" constructor — e.g. `user` in type `User`), suffix
    // it with `_` so the union keeps the bare name: `User = User_ | UserEmpty | …`.
    const ctorIface = (d: TlDef): string => {
        const base = tsName(d.name)
        return unionNames.has(base) ? `${base}_` : base
    }

    // Interface def per constructor name (dedup; first wins).
    const ctorByTs = new Map<string, TlDef>()
    for (const d of ctors) {
        const name = ctorIface(d)
        if (!ctorByTs.has(name)) ctorByTs.set(name, d)
    }

    const known = new Set<string>([...ctorByTs.keys(), ...unionNames])

    const lines: string[] = [
        '// AUTO-GENERATED by `yarn gen:types`. Do not edit by hand.',
        '// Types for the newest schema layer (post-fromJson shapes).',
        '/* eslint-disable */',
        '',
    ]

    // Constructor interfaces (sorted).
    for (const name of [...ctorByTs.keys()].sort()) {
        const def = ctorByTs.get(name)!
        const fields = fieldLines(def, known)
        lines.push(`export interface ${name} {`)
        lines.push(`    _: ${JSON.stringify(def.name)}`)
        lines.push(...fields)
        lines.push('}', '')
    }

    // Type unions (sorted).
    for (const name of [...unions.keys()].sort()) {
        const members = [...new Set(unions.get(name)!.map(d => ctorIface(d)))]
        lines.push(`export type ${name} = ${members.join(' | ')}`, '')
    }

    // RpcMethods map (sorted by method name; dedup by name — first wins).
    lines.push('export interface RpcMethods {')
    const seenMethods = new Set<string>()
    for (const m of [...methods].sort((a, b) => a.name.localeCompare(b.name))) {
        if (seenMethods.has(m.name)) continue
        seenMethods.add(m.name)
        const paramsName = `${tsName(m.name)}Params`
        const result = resultType(m.type, known)
        lines.push(`    ${JSON.stringify(m.name)}: { params: ${paramsName}; result: ${result} }`)
    }
    lines.push('}', '')

    // Method params interfaces (sorted).
    const seenParams = new Set<string>()
    for (const m of [...methods].sort((a, b) => a.name.localeCompare(b.name))) {
        const paramsName = `${tsName(m.name)}Params`
        if (seenParams.has(paramsName)) continue
        seenParams.add(paramsName)
        lines.push(`export interface ${paramsName} {`)
        lines.push(...fieldLines(m, known))
        lines.push('}', '')
    }

    return lines.join('\n')
}

function resultType(type: string, known: Set<string>): string {
    if (type === 'Bool') return 'boolean'
    if (type === 'Object' || type === 'X') return 'unknown'
    const n = tsName(type)
    return known.has(n) ? n : 'unknown'
}

/** Generates types for the schema in `schemaDir` and writes them to `outPath`. */
export function writeSchemaTs(schemaDir: string, outPath: string): void {
    mkdirSync(dirname(outPath), { recursive: true })
    writeFileSync(outPath, generateSchemaTs(schemaDir))
    console.log(`Generated -> ${outPath}`)
}

// CLI: `tsx gen-types.ts <schemaDir> <outPath>` (apps wrap this in their own
// `gen:types` script pointing at their schema). No bundled default — the
// framework no longer ships business types.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    const [schemaDir, outPath] = process.argv.slice(2)
    if (!schemaDir || !outPath) {
        console.error('usage: gen-types <schemaDir> <outPath>')
        process.exit(1)
    }
    writeSchemaTs(schemaDir, outPath)
}
