import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { parseSchemaDir } from '../tl/parser.js'
import { DEFAULT_LAYER_PREFIX, layerSnapshotName } from './layer-naming.js'

interface SnapshotEntry {
    id: string
    predicate?: string
    method?: string
    params: Array<{ name: string; type: string }>
    type: string
}

export interface FreezeResult {
    constructors: number
    methods: number
    /** Path of the JSON snapshot the gateway loads. */
    out: string
    /** Path of the human-readable `.tl` mirror (not loaded; for inspection/diffs). */
    tlOut: string
    crcWarnings: number
}

/** A single `name#id p:type … = ResultType;` line. */
function tlLine(e: SnapshotEntry): string {
    const name = e.predicate ?? e.method ?? '?'
    const params = e.params.map(p => `${p.name}:${p.type}`).join(' ')
    return `${name}#${e.id}${params ? ' ' + params : ''} = ${e.type};`
}

/** Reconstruct a readable `.tl` from the frozen IR (constructors, then methods). */
function toTlText(constructors: SnapshotEntry[], methods: SnapshotEntry[], layer: number): string {
    const lines = [`// Frozen snapshot of layer ${layer}. Generated by \`freeze\` — do not edit.`, '']
    lines.push(...constructors.map(tlLine))
    if (methods.length) lines.push('', '---functions---', '', ...methods.map(tlLine))
    return lines.join('\n') + '\n'
}

/**
 * Freezes the `.tl` schema in `schemaDir` into a per-layer snapshot
 * `<outDir>/<prefix><layer>.json` (loaded by the gateway) plus a human-readable
 * `<outDir>/<prefix><layer>.tl` mirror (for inspection/diffs; not loaded). Run
 * this when you SHIP a layer: the `.tl` you edit is the in-progress newest layer;
 * the frozen snapshot is the historical record the gateway uses to encode for
 * clients on that layer.
 *
 * The snapshot is BUSINESS-only: the immutable MTProto protocol/core types are
 * excluded (they live in @mt-tl/tl and are loaded globally), so a business
 * layer never carries protocol definitions.
 *
 * Schema ownership lives in the consumer app, so paths are explicit — apps wrap
 * this in their own `freeze` script. `prefix` controls the snapshot filename
 * (default `scheme_`); pass the SAME prefix to the gateway/studio readers.
 */
export function freezeLayer(
    schemaDir: string,
    outDir: string,
    layer: number,
    prefix = DEFAULT_LAYER_PREFIX,
): FreezeResult {
    const { defs, crcMismatches } = parseSchemaDir(schemaDir)

    const constructors: SnapshotEntry[] = []
    const methods: SnapshotEntry[] = []
    const seen = new Set<string>()
    for (const d of defs) {
        // Per-layer snapshots are BUSINESS-only. The MTProto protocol layer
        // (scheme_0_protocol + the manually-parsed core ctors `parseSchemaDir`
        // injects) is immutable and layer-independent — it lives in @mt-tl/tl
        // and the gateway always loads it globally, so it must NOT be baked into
        // each business snapshot (mirrors Telegram's split: mtproto_api vs api).
        if (d.isProtocol) continue
        if (seen.has(d.id)) continue
        seen.add(d.id)
        const params = d.params.map(p => ({ name: p.name, type: p.raw }))
        if (d.kind === 'method') methods.push({ id: d.id, method: d.name, params, type: d.type })
        else constructors.push({ id: d.id, predicate: d.name, params, type: d.type })
    }

    // Sort by constructor/method NAME (the part before `#`), not by crc32 id —
    // stable, readable snapshots + meaningful diffs. Load/decode are
    // order-independent (the registry is keyed by name/id), so this is cosmetic.
    const byName = (a: SnapshotEntry, b: SnapshotEntry) => {
        const an = a.predicate ?? a.method ?? ''
        const bn = b.predicate ?? b.method ?? ''
        return an < bn ? -1 : an > bn ? 1 : 0
    }
    constructors.sort(byName)
    methods.sort(byName)

    mkdirSync(outDir, { recursive: true })
    const out = join(outDir, layerSnapshotName(layer, 'json', prefix))
    const tlOut = join(outDir, layerSnapshotName(layer, 'tl', prefix))
    writeFileSync(out, JSON.stringify({ constructors, methods }, null, 2))
    writeFileSync(tlOut, toTlText(constructors, methods, layer))

    return {
        constructors: constructors.length,
        methods: methods.length,
        out,
        tlOut,
        crcWarnings: crcMismatches.length,
    }
}

// CLI: `tsx freeze-layer.ts <layer> <schemaDir> <outDir> [prefix]`
//   or env: `SCHEMA_DIR=… SCHEMA_LAYERS_DIR=… SCHEMA_LAYER_PREFIX=… tsx freeze-layer.ts <layer>`
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    const layer = Number(process.argv[2])
    const schemaDir = process.argv[3] || process.env.SCHEMA_DIR
    const outDir = process.argv[4] || process.env.SCHEMA_LAYERS_DIR
    const prefix = process.argv[5] || process.env.SCHEMA_LAYER_PREFIX || DEFAULT_LAYER_PREFIX
    if (!Number.isInteger(layer) || layer <= 0 || !schemaDir || !outDir) {
        console.error('usage: freeze-layer <layer> <schemaDir> <outDir> [prefix]')
        process.exit(1)
    }
    const r = freezeLayer(schemaDir, outDir, layer, prefix)
    console.log(
        `Froze layer ${layer}: ${r.constructors} constructors, ${r.methods} methods -> ${r.out} (+ ${r.tlOut})` +
            (r.crcWarnings ? `  (${r.crcWarnings} crc warnings)` : ''),
    )
}
